apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.profile.releaseName }}-deployment
  labels:
    app: {{ .Values.profile.releaseName }}
spec:
  replicas: {{ .Values.profile.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.profile.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.profile.releaseName }}
    spec:
      containers:
        - name: {{ .Values.profile.releaseName }}
          image: {{ .Values.profile.repository }}/{{ .Values.profile.image }}:{{ .Values.profile.tag }}
