apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
type: Opaque
data:
  # TODO: update mysql-username and mysql-password to match the variables that you used
  # to authenticate into the MySQL service. These should be provided in base64 encoded form.
  MYSQL_DB_USER: {{ .Values.profile.mysql.user }}
  MYSQL_DB_PASSWORD: {{ .Values.profile.mysql.password }}