apiVersion: v1
kind: Service
metadata:
  name: spring-profile-service
spec:
  selector:
    app: spring-profile
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
