weCloud:
  imageRegistry:
    gcp: "us-east1-docker.pkg.dev/gcp-docker-kubernetes-450517/task2-artifact-repo"

profile:
  # TODO: Specify values used in deployment.yaml
  releaseName: "spring-profile"
  replicaCount: 3
  repository: "us-east1-docker.pkg.dev/gcp-docker-kubernetes-450517/task2-artifact-repo"
  image: "clouduser/project"
  tag: "1.0.1"
  # TODO: Specify values used in service.yaml
  service: 
    type: "LoadBalancer"
    port: 80
    targetPort: 8080
  # TODO: Specify values for MySQL environment variables
  mysql:
    host: "mysql-profile.default.svc.cluster.local"
    user: YXJpaGFudHNoZXRo
    password: RXRlcm5pYUAxMjM=
    port: "3306"
