apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  # TODO: update mysql-username and mysql-password to match the variables that you used
  # to authenticate into the MySQL service. These should be provided in base64 encoded form.
  mysql-username: {{ .Values.chat.mysql.user }}
  mysql-password: {{ .Values.chat.mysql.password }}