apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.login.releaseName }}-deployment"
  labels:
    app: "{{ .Values.login.releaseName }}"
spec:
  replicas: {{ .Values.login.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.login.releaseName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.login.releaseName }}"
    spec:
      containers:
        - name: "{{ .Values.login.releaseName }}"
          image: "{{ .Values.login.repository }}/{{ .Values.login.image }}:{{ .Values.login.tag }}"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: "{{ .Values.login.releaseName }}-config"
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "login-secret"
                  key: mysql-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "login-secret"
                  key: mysql-password
          resources:
            requests:
              cpu: {{ .Values.login.hpa.cpuRequest }}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.login.releaseName }}-autoscaling"
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: {{ .Values.login.hpa.minReplicas }}
  maxReplicas: {{ .Values.login.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.login.hpa.targetCPUUtilizationPercentage }}
